spring:
    application:
        name: freelance
    profiles:
        active: dev
debug: true
logging:
    level:
        org.springframework.boot.autoconfigure: ERROR
        org.springframework.core: ERROR